"""Example of using OrchestratorAgent and PlannerAgent together.

This example demonstrates how to use the OrchestratorAgent and PlannerAgent
from the Orqest framework to create a plan for a user query.
"""
import asyncio
import logging
import sys
from pathlib import Path
from typing import List, Dict, Any, Optional

# Add the project root to the Python path
sys.path.append(str(Path(__file__).parent.parent))

from examples.agents import GlobalState, OrchestratorAgent

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

async def run_orchestrator(
    query: str,
    orchestrator_config: Optional[Dict[str, Any]] = None,
    planner_config: Optional[Dict[str, Any]] = None
) -> List[str]:
    """Run the orchestrator agent with a user query.
    
    Args:
        query: The user query to process.
        orchestrator_config: Optional configuration for the orchestrator agent.
        planner_config: Optional configuration for the planner agent.
        
    Returns:
        The plan generated by the orchestrator agent.
    """
    # Create an orchestrator agent with optional custom configuration
    # This demonstrates the new flexible initialization pattern
    if orchestrator_config and planner_config:
        # Create with both orchestrator and planner configuration
        orchestrator = OrchestratorAgent(
            **orchestrator_config,
            planner_config=planner_config
        )
        logger.info(f"Created orchestrator with custom config and planner config")
    elif orchestrator_config:
        # Create with just orchestrator configuration
        orchestrator = OrchestratorAgent(**orchestrator_config)
        logger.info(f"Created orchestrator with custom config")
    elif planner_config:
        # Create with just planner configuration
        orchestrator = OrchestratorAgent(planner_config=planner_config)
        logger.info(f"Created orchestrator with planner config")
    else:
        # Create with default configuration
        orchestrator = OrchestratorAgent()
        logger.info(f"Created orchestrator with default config")
    
    # Initialize state with the user query
    state = GlobalState()
    state.add_message("user", query)
    
    # Log the query
    logger.info(f"Processing query: {query}")
    
    # Run the orchestrator agent
    try:
        # The orchestrator will call the planner agent as needed
        result_state = await orchestrator.run(state)
        
        # Log the result
        if result_state.plan:
            logger.info(f"Generated plan with {len(result_state.plan)} steps")
            for i, step in enumerate(result_state.plan, 1):
                logger.info(f"Step {i}: {step}")
        else:
            logger.warning("No plan was generated")
            
        return result_state.plan
        
    except Exception as e:
        logger.error(f"Error running orchestrator: {str(e)}")
        return []

async def main():
    """Run the example demonstrating different agent configurations."""
    # Example queries
    queries = [
        "What are the steps to bake a chocolate cake?",
        "How do I plan a weekend trip to the mountains?",
        "What's the process for learning to play the guitar?"
    ]
    
    # Example 1: Default configuration
    logger.info("\n" + "=" * 50)
    logger.info("Example 1: Default Configuration")
    logger.info("=" * 50)
    plan = await run_orchestrator(queries[0])
    if plan:
        print(f"\nPlan for: {queries[0]} (Default Configuration)")
        for i, step in enumerate(plan, 1):
            print(f"{i}. {step}")
        print()
    
    # Wait a bit between examples
    await asyncio.sleep(1)
    
    # Example 2: Custom orchestrator configuration
    logger.info("\n" + "=" * 50)
    logger.info("Example 2: Custom Orchestrator Configuration")
    logger.info("=" * 50)
    orchestrator_config = {
        "agent_name": "custom_orchestrator",
        "retries": 3,
        "system_prompt": """You are a specialized orchestrator focused on detailed planning.
        Your goal is to create comprehensive, step-by-step plans for any task.
        Always consider all aspects of the task and provide thorough instructions."""
    }
    plan = await run_orchestrator(queries[1], orchestrator_config=orchestrator_config)
    if plan:
        print(f"\nPlan for: {queries[1]} (Custom Orchestrator Configuration)")
        for i, step in enumerate(plan, 1):
            print(f"{i}. {step}")
        print()
    
    # Wait a bit between examples
    await asyncio.sleep(1)
    
    # Example 3: Custom planner configuration
    logger.info("\n" + "=" * 50)
    logger.info("Example 3: Custom Planner Configuration")
    logger.info("=" * 50)
    planner_config = {
        "agent_name": "custom_planner",
        "retries": 3,
        "system_prompt": """You are a specialized planning agent focused on actionable steps.
        Your goal is to break down complex tasks into simple, executable steps.
        Always provide concrete actions that can be followed without ambiguity."""
    }
    plan = await run_orchestrator(queries[2], planner_config=planner_config)
    if plan:
        print(f"\nPlan for: {queries[2]} (Custom Planner Configuration)")
        for i, step in enumerate(plan, 1):
            print(f"{i}. {step}")
        print()
    
    # Example 4: Both custom configurations
    logger.info("\n" + "=" * 50)
    logger.info("Example 4: Both Custom Configurations")
    logger.info("=" * 50)
    orchestrator_config = {
        "agent_name": "custom_orchestrator_2",
        "retries": 2,
    }
    planner_config = {
        "agent_name": "custom_planner_2",
        "retries": 2,
    }
    # Use the first query again to compare with default configuration
    plan = await run_orchestrator(
        queries[0], 
        orchestrator_config=orchestrator_config,
        planner_config=planner_config
    )
    if plan:
        print(f"\nPlan for: {queries[0]} (Both Custom Configurations)")
        for i, step in enumerate(plan, 1):
            print(f"{i}. {step}")
        print()

if __name__ == "__main__":
    # Run the example
    asyncio.run(main())