"""Example of using OrchestratorAgent and PlannerAgent together.

This example demonstrates how to use the OrchestratorAgent and PlannerAgent
from the Orqest framework to create a plan for a user query.
"""
import asyncio
import logging
import sys
from pathlib import Path
from typing import List

# Add the project root to the Python path
sys.path.append(str(Path(__file__).parent.parent))

from examples.agents import GlobalState, OrchestratorAgent

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

async def run_orchestrator(query: str) -> List[str]:
    """Run the orchestrator agent with a user query.
    
    Args:
        query: The user query to process.
        
    Returns:
        The plan generated by the orchestrator agent.
    """
    # Create an orchestrator agent (which internally creates a planner agent)
    orchestrator = OrchestratorAgent()
    
    # Initialize state with the user query
    state = GlobalState()
    state.add_message("user", query)
    
    # Log the query
    logger.info(f"Processing query: {query}")
    
    # Run the orchestrator agent
    try:
        # The orchestrator will call the planner agent as needed
        result_state = await orchestrator.run(state)
        
        # Log the result
        if result_state.plan:
            logger.info(f"Generated plan with {len(result_state.plan)} steps")
            for i, step in enumerate(result_state.plan, 1):
                logger.info(f"Step {i}: {step}")
        else:
            logger.warning("No plan was generated")
            
        return result_state.plan
        
    except Exception as e:
        logger.error(f"Error running orchestrator: {str(e)}")
        return []

async def main():
    """Run the example."""
    # Example queries
    queries = [
        "What are the steps to bake a chocolate cake?",
        "How do I plan a weekend trip to the mountains?",
        "What's the process for learning to play the guitar?"
    ]
    
    # Process each query
    for query in queries:
        logger.info(f"\n{'=' * 50}\nProcessing: {query}\n{'=' * 50}")
        plan = await run_orchestrator(query)
        
        # Print the plan
        if plan:
            print(f"\nPlan for: {query}")
            for i, step in enumerate(plan, 1):
                print(f"{i}. {step}")
            print()
        else:
            print(f"\nNo plan was generated for: {query}\n")
        
        # Wait a bit between queries
        await asyncio.sleep(1)

if __name__ == "__main__":
    # Run the example
    asyncio.run(main())