"""State models for Orqest agents."""
import logging
from typing import Any, List, Optional, Dict

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

class GlobalState(BaseModel):
    """Global state for agents.
    
    This class represents the shared state that can be used by different agents
    in the Orqest framework. It includes methods for managing messages and
    retrieving the latest messages from different roles.
    
    Attributes:
        messages: List of messages in the conversation.
        plan: Current plan generated by agents.
        chat_history: History of the chat for context.
    """
    messages: List[Dict[str, Any]] = Field(default_factory=list)
    plan: List[str] = Field(default_factory=list)
    chat_history: List[str] = Field(default_factory=list)

    def add_message(self, role: str, content: str) -> None:
        """Add a message to the global state.
        
        Args:
            role: The role of the message sender (e.g., "user", "assistant").
            content: The content of the message.
        """
        self.messages.append({"role": role, "content": content})

    def get_latest_user_message(self) -> Optional[str]:
        """Get the latest user message from the global state.
        
        Returns:
            The content of the latest user message, or None if no user message exists.
        """
        for message in reversed(self.messages):
            if message["role"] == "user":
                return message["content"]
        return None

    def get_latest_assistant_message(self) -> Optional[str]:
        """Get the latest assistant message from the global state.
        
        Returns:
            The content of the latest assistant message, or None if no assistant message exists.
        """
        for message in reversed(self.messages):
            if message["role"] == "assistant":
                return message["content"]
        return None